#from https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md

name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_AUTHOR_NAME: github-actions
      GIT_AUTHOR_EMAIL: 44210433+github-actions@users.noreply.github.com
      GIT_COMMITTER_NAME: github-actions
      GIT_COMMITTER_EMAIL: 44210433+github-actions@users.noreply.github.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Release
        run: npx semantic-release
